## first stage
FROM node:21-slim AS builder

WORKDIR /usr/src/app

COPY ./package.json ./

RUN npm install

COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

## second stage
FROM caddy:2.7.6-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build /srv

EXPOSE 80

EXPOSE 443